[package]
name = "cql-stress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
async-trait = "0.1.52"
futures = "0.3.19"
hdrhistogram = "7.5.0"
scylla = "0.3.1"
parking_lot = "0.12.0"
rand = "0.8"
rand_distr = "0.4"
rand_pcg = "0.3"
sha2 = "0.10"
thread_local = "1.1.4"
tokio = { version = "1.15.0", features = ["full"] } # TODO: Include only necessary features
